# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arscK0IFM64b8dJAhBSf8kDb4jOHpno3
"""

import streamlit as st
import requests

# Flask server URL
FLASK_SERVER_URL = 'http://localhost:5000'

# Streamlit app
def main():
    st.title('Sentiment Analysis')

    # User input
    text = st.text_area('Enter text here')

    # Button to analyze sentiment
    if st.button('Analyze'):
        # Make request to Flask route
        response = requests.post(f'{FLASK_SERVER_URL}/analyze', data={'text': text})

        # Display sentiment result
        if response.status_code == 200:
            result = response.json()['result']
            st.write(f'Sentiment: {result}')
        else:
            st.error('Error analyzing sentiment')

if __name__ == '__main__':
    main()