<<<<<<< HEAD
version: '3'

services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
=======
version: '3'

services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
>>>>>>> origin/main
